sonar.projectKey=organizationsapi

sonar.projectName=organizationsapi

sonar.projectVersion=1.0

sonar.projectBaseDir=.


sonar.sources=src/main/java

sonar.tests=src/test/java

sonar.java.binaries=target/classes

# SonarQube server

sonar.host.url=http://localhost:9000

sonar.token=sqp_9f85b7048ee91ca34aedeb13af96735b563f90d6

# Encoding

sonar.sourceEncoding=UTF-8

# Coverage

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.junit.reportPaths=target/surefire-reports

# Exclusions/Inclusions

sonar.coverage.exclusions=**/config/**,**/dto/**,**/entity/**,**/exception/**,**/repository/**,**/Application*.java,**/PlanifikausersapiApplication.java